name: lawlink360
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8


  camera: ^0.11.0+2
  image: ^4.2.0
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  flutter_box_transform: ^0.4.7
  crop_your_image: ^2.0.0

  google_mlkit_translation: ^0.12.0
  google_mlkit_text_recognition: ^0.14.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  clipboard: ^0.1.3

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.1

  # Social Logins
  google_sign_in: ^7.0.0


  # Biometric Authentication
  local_auth: ^2.1.7

  # Secure Storage for Session Management
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.3

  # State Management
  provider: ^6.0.5

  # Loading Animations
  loading_animation_widget: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/backgrounds/
    - assets/illustrations/
    - assets/splash/


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0B1F3A"
flutter_native_splash:
  color: "#0B1F3A"
  android: true
  ios: false
  android_12:
    color: "#0B1F3A"